'use strict';
/**
 * datamosh_transition.js — A -> datamosh melt -> B, as a single preset.
 *
 * Classic cross-clip datamosh: clip A plays normally up to the transition
 * point, then clip B's frames are spliced in with their leading keyframe
 * physically removed. With no valid reference frame of its own, the
 * decoder falls back to A's last picture and keeps applying B's real motion
 * vectors and residuals on top of it — so B's motion "paints" itself over
 * A's frozen image, and the picture gradually resolves into B as more of
 * its frames arrive.
 *
 * This is built on top of datamosh.js's ffgac-based encode (forced motion
 * vectors, no I-macroblock refresh) so the transition can be as short and
 * punchy or as long and smeary as you want, and — if you choose — never
 * fully "clean up" back to a normal B keyframe at all.
 *
 * Requires: ffgac + ffedit (FFglitch) and ffmpeg + ffprobe (regular FFmpeg).
 * Same binaries as datamosh.js — no new dependencies.
 */

const fs   = require('fs');
const fsp  = require('fs/promises');
const os   = require('os');
const path = require('path');
const { run, resolveBin, fileExists, probeFps, DatamoshError } = require('./datamosh.js');

// MPEG-4 part 2 start codes we need to walk the raw elementary stream.
const START_CODE = Buffer.from([0x00, 0x00, 0x01]);
const VOP_CODE   = Buffer.from([0x00, 0x00, 0x01, 0xb6]);

/**
 * Local run() that also tracks the child PID so an external abortSignal
 * can SIGKILL in-flight ffmpeg/ffgac children. Same error shape as the
 * one in datamosh.js (DatamoshError with stderr tail).
 */
function runWithAbort(cmd, stepName, spawned) {
  return new Promise((resolve, reject) => {
    const { execFile } = require('child_process');
    const child = execFile(cmd[0], cmd.slice(1), { maxBuffer: 64 * 1024 * 1024 }, (err, stdout, stderr) => {
      spawned.delete(child.pid);
      if (err) {
        if (err.code === 'ENOENT') {
          return reject(new DatamoshError(
            `${stepName}: could not find executable '${cmd[0]}'. ` +
            `Check that the path is correct and the binary is executable.`,
            { step: stepName }
          ));
        }
        if (err.signal === 'SIGKILL') {
          return reject(new DatamoshError(
            `${stepName}: aborted (client disconnected)`,
            { step: stepName }
          ));
        }
        const tail = String(stderr || '').trim().split('\n').slice(-25).join('\n');
        return reject(new DatamoshError(
          `${stepName} failed (exit ${err.code}):\n${tail}`,
          { step: stepName, stderrTail: tail }
        ));
      }
      resolve({ stdout, stderr });
    });
    spawned.add(child.pid);
  });
}

async function probeResolution(ffprobeBin, inputPath) {
  const { stdout } = await run([
    ffprobeBin, '-v', 'error',
    '-select_streams', 'v:0',
    '-show_entries', 'stream=width,height',
    '-of', 'json',
    inputPath,
  ], 'ffprobe (reading resolution)');

  let data;
  try { data = JSON.parse(stdout); }
  catch (e) { throw new DatamoshError(`ffprobe returned non-JSON for resolution: ${stdout.slice(0, 200)}`); }
  const s = data?.streams?.[0];
  if (!s?.width || !s?.height) throw new DatamoshError(`ffprobe did not report width/height for ${inputPath}`);
  return [parseInt(s.width, 10), parseInt(s.height, 10)];
}

function writeBPictTypeScript(filePath, settleFrame, normalGop) {
  // Frame 0 must still be encoded as a real I-frame (ffgac needs a valid
  // first reference to encode against) — we remove that I-frame's actual
  // data later, at the byte level, once encoding is done. If settleFrame
  // is given, B resumes normal periodic keyframes after that many frames
  // so the mosh eventually cleans up into a crisp picture of B; if null,
  // B never gets another real keyframe and the blend never fully resolves.
  const body = settleFrame == null
    ? '    if (f === 0) return "I";\n    return "P";'
    : `    if (f === 0) return "I";
    if (f < ${settleFrame}) return "P";
    return (f % ${normalGop} === 0) ? "I" : "P";`;

  const script = `// Auto-generated by fg · ffgac pict_type_script for clip B
// Frame 0 = real I (we strip it at the byte level after encoding).
// Until settle_frame (if any), every frame is P — never refreshed.
let frame_num = 0;

export function setup() {
  frame_num = 0;
}

export function pict_type_func() {
  const f = frame_num++;
${body}
}
`;
  fs.writeFileSync(filePath, script);
}

/**
 * Prepare clip B's elementary stream for bitstream-level splicing into
 * clip A. Three things have to go, not just the first VOP:
 *
 *   1. B's VOL header. If left in, the decoder treats the A→B boundary
 *      as a NEW stream and re-syncs there (inserting a clean keyframe
 *      that kills the mosh). Stripping it makes the decoder keep using
 *      A's parameters across the splice.
 *
 *   2. The first VOP (B's frame 0). The script tells ffgac to make this
 *      a real I-frame, so the surviving stream has nothing to reference.
 *
 *   3. The second VOP (B's frame 1). This is a ffgac quirk: even when
 *      the pict_type_script returns "P" for frame 1, ffgac still emits
 *      an I-frame there. Without stripping it, the decoder would treat
 *      the splice as "B starts with a clean picture" and the mosh
 *      effect would only last for one frame. Dropping it as well gives
 *      us a clean P-frame chain back to A.
 *
 * The remaining bytes are B's VOPs from frame 2 onward, all P-frames —
 * ready to be concatenated directly after A's last VOP. The decoder
 * has nothing to reference for them, so it falls back to A's last
 * picture, which is the actual melt mechanism.
 */
function stripLeadingIFramesAndHeader(data) {
  const firstVop = data.indexOf(VOP_CODE);
  if (firstVop === -1) {
    throw new DatamoshError(
      "Could not find a frame header (0x000001B6) in clip B's encoded " +
      "stream — the encode may have failed or used an unexpected codec."
    );
  }
  // Drop everything up to the first VOP (the VOL header).
  const afterVol = data.subarray(firstVop);
  // Drop the first VOP (B's frame 0, encoded as I by the script).
  const afterFirst = afterVol.indexOf(VOP_CODE, VOP_CODE.length);
  if (afterFirst === -1) return Buffer.alloc(0);
  // Drop the second VOP (B's frame 1, ffgac inserts an I here despite
  // the script). After this point, every VOP in B is a P-frame.
  const afterSecond = afterVol.subarray(afterFirst)
    .indexOf(VOP_CODE, VOP_CODE.length);
  return afterSecond === -1 ? Buffer.alloc(0) : afterVol.subarray(afterFirst).subarray(afterSecond);
}

/**
 * Build an A -> datamosh melt -> B transition.
 *
 * @param {object} opts
 * @param {string} opts.clipAPath            — source video A
 * @param {string} opts.clipBPath            — source video B
 * @param {string} opts.outputPath           — destination .avi path
 * @param {number} opts.transitionAtSeconds  — point in clip A where B starts bleeding in
 * @param {number|null} [opts.meltDurationSeconds] — how long after the transition before
 *        B gets a clean keyframe (picture fully "resolves"). null/undefined = never.
 * @param {string} [opts.ffgacBin]           — override ffgac binary path
 * @param {string} [opts.ffeditBin]          — override ffedit binary path
 * @param {string} [opts.ffmpegBin]          — override ffmpeg binary path
 * @param {string} [opts.ffprobeBin]         — override ffprobe binary path
 * @param {number} [opts.normalGop=30]       — keyframe interval after melt settles (if at all)
 * @param {number} [opts.quality=3]          — ffgac -q:v (2=best, 31=worst)
 * @param {boolean} [opts.includeAudio=true] — hard-cut audio: A's audio up to the
 *        transition, then B's. No crossfade.
 * @param {string} [opts.workDir]            — override temp dir (else a fresh mkdtemp)
 * @param {AbortSignal} [opts.abortSignal]   — when `.aborted`, the pipeline
 *        throws a DatamoshError between steps and its spawned ffmpeg/ffgac
 *        children get a best-effort SIGKILL.
 * @param {function} [opts.onProgress]       — called between steps with
 *        `(stepIndex, totalSteps, stepLabel, fraction)` so the server can
 *        report real progress to a polling client.
 *
 * @returns {Promise<{outputPath:string, fps:number, frameWidth:number, frameHeight:number,
 *                    transitionFrame:number, settleFrame:number|null}>}
 */
async function datamoshTransition(opts) {
  const {
    clipAPath, clipBPath, outputPath,
    transitionAtSeconds,
    meltDurationSeconds = null,
    ffgacBin, ffeditBin, ffmpegBin, ffprobeBin,
    normalGop = 30, quality = 3,
    includeAudio = true,
    workDir,
    abortSignal,
    onProgress,
  } = opts;

  // Step weights — the ffgac B-encode is by far the slowest, so it gets
  // half the bar; everything else is roughly equal.
  const STEPS = [
    { label: 'Probing clip A',           weight: 0.05 },
    { label: 'Encoding clip B (ffgac)',  weight: 0.55 },
    { label: 'Stripping clip B headers', weight: 0.10 },
    { label: 'Remuxing combined video',  weight: 0.10 },
    { label: 'Extracting A audio',       weight: 0.05 },
    { label: 'Extracting B audio',       weight: 0.05 },
    { label: 'Concatenating audio',      weight: 0.05 },
    { label: 'Muxing final output',      weight: 0.05 },
  ];
  let stepIdx = -1;
  let stepStart = 0;
  const reportProgress = (label) => {
    stepIdx += 1;
    const total = STEPS.length;
    const done  = STEPS.slice(0, stepIdx).reduce((s, x) => s + x.weight, 0);
    stepStart = done;
    try { onProgress?.(stepIdx, total, label, done); } catch {}
  };
  const reportSub = (frac) => {
    // Within the current step, fudge progress linearly.
    const w = STEPS[stepIdx]?.weight || 0;
    const done = stepStart + Math.max(0, Math.min(1, frac)) * w;
    try { onProgress?.(stepIdx, STEPS.length, STEPS[stepIdx]?.label || '', done); } catch {}
  };

  const ffgac   = resolveBin('FFGAC_BIN',   ffgacBin,   'ffgac');
  const ffedit  = resolveBin('FFEDIT_BIN',  ffeditBin,  'ffedit');
  const ffmpeg  = resolveBin('FFMPEG_BIN',  ffmpegBin,  'ffmpeg');
  const ffprobe = resolveBin('FFPROBE_BIN', ffprobeBin, 'ffprobe');

  // Track ffmpeg/ffgac child PIDs so we can SIGKILL them on abort.
  const spawned = new Set();
  const checkAbort = () => {
    if (abortSignal?.aborted) {
      for (const pid of spawned) { try { process.kill(pid, 'SIGKILL'); } catch {} }
      throw new DatamoshError('aborted: client disconnected before pipeline finished');
    }
  };

  if (!await fileExists(clipAPath)) throw new DatamoshError(`clip_a not found: ${clipAPath}`);
  if (!await fileExists(clipBPath)) throw new DatamoshError(`clip_b not found: ${clipBPath}`);
  if (!(transitionAtSeconds >= 0)) {
    throw new DatamoshError('transitionAtSeconds must be >= 0');
  }
  if (meltDurationSeconds != null && !(meltDurationSeconds >= 0)) {
    throw new DatamoshError('meltDurationSeconds must be >= 0 (or null)');
  }
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });

  // Probe A for fps + resolution. B is scaled to match.
  reportProgress('Probing clip A');
  const fps = await probeFps(ffprobe, clipAPath);
  const [width, height] = await probeResolution(ffprobe, clipAPath);

  const transitionFrame = Math.max(1, Math.round(transitionAtSeconds * fps));
  const settleFrame     = meltDurationSeconds == null
    ? null
    : Math.round(meltDurationSeconds * fps);

  const usingExternalWorkDir = !!workDir;
  const tmpDir = workDir
    ? path.resolve(workDir)
    : await fsp.mkdtemp(path.join(os.tmpdir(), 'fg-datamosh-trans-'));
  fs.mkdirSync(tmpDir, { recursive: true });

  try {
    const partAEs         = path.join(tmpDir, 'part_a.m4v');
    const partBFull       = path.join(tmpDir, 'part_b_full.avi');
    const partBEs         = path.join(tmpDir, 'part_b.m4v');
    const partBStripped   = path.join(tmpDir, 'part_b_stripped.m4v');
    const combinedEs      = path.join(tmpDir, 'combined.m4v');
    const videoOnly       = path.join(tmpDir, 'video_only.avi');
    const bPictScript     = path.join(tmpDir, 'b_pict_type.js');

    // 1. Clip A, up to the transition point, as a plain MPEG-4 elementary
    //    stream — same codec params B will be encoded with, so the two
    //    streams can be concatenated at the bitstream level.
    checkAbort();
    await runWithAbort([
      ffmpeg, '-y',
      '-i', clipAPath,
      '-t', String(transitionAtSeconds),
      '-an',
      '-c:v', 'mpeg4', '-q:v', String(quality),
      '-pix_fmt', 'yuv420p',
      '-r', String(fps),
      '-f', 'm4v',
      partAEs,
    ], 'ffmpeg (clip A pre-transition segment)', spawned);

    // 2. Clip B, full duration, scaled to fit A's frame while preserving
    //    B's own aspect ratio (letter/pillarbox with black bars if the
    //    ratios differ), encoded with ffgac's forced-motion-vector /
    //    no-refresh settings so the blend can smear for as long as we want.
    checkAbort();
    reportProgress('Encoding clip B (ffgac)');
    writeBPictTypeScript(bPictScript, settleFrame, normalGop);
    await runWithAbort([
      ffgac, '-y',
      '-i', clipBPath,
      '-vf', [
        `scale=${width}:${height}:force_original_aspect_ratio=decrease`,
        `pad=${width}:${height}:(ow-iw)/2:(oh-ih)/2:black`,
        'setsar=1',
        `fps=${fps}`,
      ].join(','),
      '-an',
      '-c:v', 'mpeg4',
      '-mpv_flags', '+forcemv+nopimb',
      '-g', '999999', '-sc_threshold', '1000000000',
      '-pict_type_script', bPictScript,
      '-q:v', String(quality),
      partBFull,
    ], 'ffgac (clip B encode)', spawned);

    // 3. Pull B's raw elementary stream out of the container, then strip
    //    its leading I-frame at the byte level — the actual "no valid
    //    reference frame" trick.
    checkAbort();
    reportProgress('Stripping clip B headers');
    await runWithAbort([
      ffmpeg, '-y',
      '-i', partBFull,
      '-c:v', 'copy', '-an',
      '-f', 'm4v',
      partBEs,
    ], 'ffmpeg (extract clip B elementary stream)', spawned);

    checkAbort();
    const bRaw  = await fsp.readFile(partBEs);
    const bCut  = stripLeadingIFramesAndHeader(bRaw);
    await fsp.writeFile(partBStripped, bCut);

    // 4. Concatenate the two raw streams and remux into a real container.
    const aRaw = await fsp.readFile(partAEs);
    await fsp.writeFile(combinedEs, Buffer.concat([aRaw, bCut]));

    checkAbort();
    reportProgress('Remuxing combined video');
    await runWithAbort([
      ffmpeg, '-y',
      '-r', String(fps),
      '-i', combinedEs,
      '-c:v', 'copy',
      videoOnly,
    ], 'ffmpeg (remux combined video)', spawned);

    if (includeAudio) {
      const audioA       = path.join(tmpDir, 'audio_a.aac');
      const audioB       = path.join(tmpDir, 'audio_b.aac');
      const audioList    = path.join(tmpDir, 'audio_list.txt');
      const audioCombined = path.join(tmpDir, 'audio_combined.aac');

      checkAbort();
      reportProgress('Extracting A audio');
      await runWithAbort([
        ffmpeg, '-y', '-i', clipAPath,
        '-t', String(transitionAtSeconds),
        '-vn', '-c:a', 'aac',
        audioA,
      ], 'ffmpeg (clip A audio)', spawned);
      checkAbort();
      reportProgress('Extracting B audio');
      await runWithAbort([
        ffmpeg, '-y', '-i', clipBPath,
        '-vn', '-c:a', 'aac',
        audioB,
      ], 'ffmpeg (clip B audio)', spawned);
      await fsp.writeFile(
        audioList,
        `file '${path.basename(audioA)}'\nfile '${path.basename(audioB)}'\n`
      );
      checkAbort();
      reportProgress('Concatenating audio');
      await runWithAbort([
        ffmpeg, '-y',
        '-f', 'concat', '-safe', '0',
        '-i', audioList,
        '-c:a', 'copy',
        audioCombined,
      ], 'ffmpeg (concat audio)', spawned);
      checkAbort();
      reportProgress('Muxing final output');
      await runWithAbort([
        ffmpeg, '-y',
        '-i', videoOnly, '-i', audioCombined,
        '-c:v', 'copy', '-c:a', 'aac',
        '-shortest',
        outputPath,
      ], 'ffmpeg (mux final audio+video)', spawned);
    } else {
      checkAbort();
      reportProgress('Copying video-only output');
      await fsp.copyFile(videoOnly, outputPath);
    }
    reportSub(1);
    try { onProgress?.(STEPS.length, STEPS.length, 'Done', 1); } catch {}

    return {
      outputPath,
      fps,
      frameWidth: width,
      frameHeight: height,
      transitionFrame,
      settleFrame,
    };
  } finally {
    // Make sure no ffmpeg/ffgac child outlives a failing/aborted pipeline.
    for (const pid of spawned) { try { process.kill(pid, 'SIGKILL'); } catch {} }
    if (!usingExternalWorkDir) {
      try { await fsp.rm(tmpDir, { recursive: true, force: true }); } catch {}
    }
  }
}

/**
 * Streaming variant of `datamoshTransition` for privacy-first pipelines.
 *
 * Both inputs (already on disk) are read in place, the pipeline runs into
 * a private temp file, then the result is streamed via the given Response.
 * Temp files are removed in `finally`, so the server never persists the
 * output (and never serves it via a URL after the response ends).
 *
 * @param {object} opts
 * @param {string} opts.clipAPath
 * @param {string} opts.clipBPath
 * @param {import('http').ServerResponse} opts.res
 * @param {string} [opts.filename]
 * @param {object} [...rest] — passed through to `datamoshTransition()`
 */
async function datamoshTransitionStream(opts) {
  const { clipAPath, clipBPath, res, filename = 'transition.avi', ...rest } = opts;
  const { pipeline } = require('stream/promises');

  const tmpOut = path.join(os.tmpdir(),
    `fg-mosh-trans-out-${process.pid}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}.avi`);
  const tmpDir = await fsp.mkdtemp(path.join(os.tmpdir(), 'fg-datamosh-trans-'));

  // External abort signal so the route can cancel the pipeline if the
  // browser disconnects mid-render (or during the upload itself).
  const ac = new AbortController();
  const onClose = () => { if (!res.writableEnded) ac.abort(new Error('client closed connection')); };
  res.on('close', onClose);

  try {
    const result = await datamoshTransition({
      ...rest,
      clipAPath,
      clipBPath,
      outputPath: tmpOut,
      workDir:    tmpDir,
      abortSignal: ac.signal,
    });

    // If the client went away while we were building, don't bother writing
    // headers — they'd just hit a dead socket.
    if (ac.signal.aborted) return result;

    const stat = await fsp.stat(tmpOut);
    res.setHeader('Content-Type',        'video/x-msvideo');
    res.setHeader('Content-Length',      String(stat.size));
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.setHeader('Cache-Control',       'no-store');
    res.setHeader('X-Fg-Fps',             String(result.fps));
    res.setHeader('X-Fg-Frame-Width',     String(result.frameWidth));
    res.setHeader('X-Fg-Frame-Height',    String(result.frameHeight));
    res.setHeader('X-Fg-Transition-Frame', String(result.transitionFrame));
    if (result.settleFrame != null) {
      res.setHeader('X-Fg-Settle-Frame', String(result.settleFrame));
    }

    await pipeline(
      fs.createReadStream(tmpOut),
      res,
      { end: true }
    );

    return result;
  } finally {
    res.off('close', onClose);
    try { await fsp.rm(tmpOut, { force: true }); } catch {}
    try { await fsp.rm(tmpDir, { recursive: true, force: true }); } catch {}
  }
}

module.exports = { datamoshTransition, datamoshTransitionStream };
