'use strict';
/**
 * datamosh.js — one-shot "clean start, then melt forever" datamosh pipeline.
 *
 * Wraps FFglitch's ffgac + ffedit into a single call:
 *   1. ffgac re-encodes the source as MPEG-4, forcing motion vectors everywhere,
 *      disabling I-macroblock refresh, and killing every automatic keyframe
 *      after frame 0 (via a generated pict_type_script).
 *   2. ffedit then freezes the motion vectors from the chosen mosh point on,
 *      so every later frame keeps replaying stale motion against residual data
 *      that no longer matches — producing the classic compounding "melt" that
 *      never resets.
 *
 * Requires the FFglitch binaries `ffgac` and `ffedit` from
 * https://ffglitch.org — either on PATH or passed via the FFGAC_BIN /
 * FFEDIT_BIN env vars (or the `ffgac_bin` / `ffedit_bin` kwargs).
 * Also requires `ffprobe` (from a normal FFmpeg install).
 */

const { execFile } = require('child_process');
const fs           = require('fs');
const fsp          = require('fs/promises');
const os           = require('os');
const path         = require('path');
const { pipeline } = require('stream/promises');

class DatamoshError extends Error {
  constructor(message, { step, stderrTail } = {}) {
    super(message);
    this.name   = 'DatamoshError';
    this.step   = step;
    if (stderrTail) this.stderrTail = stderrTail;
  }
}

/** Run an external command. Resolves with {stdout, stderr}; rejects with
 *  a DatamoshError carrying the last ~25 lines of stderr for UI surfacing. */
function run(cmd, stepName) {
  return new Promise((resolve, reject) => {
    execFile(cmd[0], cmd.slice(1), { maxBuffer: 64 * 1024 * 1024 }, (err, stdout, stderr) => {
      if (err) {
        if (err.code === 'ENOENT') {
          return reject(new DatamoshError(
            `${stepName}: could not find executable '${cmd[0]}'. ` +
            `Check that the path is correct and the binary is executable.`,
            { step: stepName }
          ));
        }
        const tail = String(stderr || '').trim().split('\n').slice(-25).join('\n');
        return reject(new DatamoshError(
          `${stepName} failed (exit ${err.code}):\n${tail}`,
          { step: stepName, stderrTail: tail }
        ));
      }
      resolve({ stdout, stderr });
    });
  });
}

function resolveBin(envName, override, fallback) {
  // 1. explicit override kwarg wins
  // 2. then env var (e.g. FFPROBE_BIN)
  // 3. then the bare binary name on PATH (e.g. "ffprobe")
  return override || process.env[envName] || fallback;
}

async function fileExists(p) {
  try { await fsp.access(p); return true; } catch { return false; }
}

async function probeFps(ffprobeBin, inputPath) {
  const { stdout } = await run([
    ffprobeBin, '-v', 'error',
    '-select_streams', 'v:0',
    '-show_entries', 'stream=r_frame_rate',
    '-of', 'json',
    inputPath,
  ], 'ffprobe (reading fps)');

  let data;
  try { data = JSON.parse(stdout); }
  catch (e) { throw new DatamoshError(`ffprobe returned non-JSON: ${stdout.slice(0, 200)}`); }

  const rate = data?.streams?.[0]?.r_frame_rate;
  if (!rate) throw new DatamoshError('ffprobe did not report r_frame_rate');
  const [num, den] = rate.split('/');
  const fps = parseFloat(num) / parseFloat(den || '1');
  if (!isFinite(fps) || fps <= 0) throw new DatamoshError(`Invalid framerate from ffprobe: ${rate}`);
  return fps;
}

async function probeFrameCount(ffprobeBin, inputPath) {
  // Best-effort — not required for the pipeline, so failures are non-fatal.
  try {
    const { stdout } = await run([
      ffprobeBin, '-v', 'error',
      '-select_streams', 'v:0',
      '-count_frames',
      '-show_entries', 'stream=nb_read_frames',
      '-of', 'json',
      inputPath,
    ], 'ffprobe (counting frames)');
    const n = parseInt(JSON.parse(stdout)?.streams?.[0]?.nb_read_frames, 10);
    return Number.isFinite(n) ? n : null;
  } catch { return null; }
}

function writePictTypeScript(filePath, moshStartFrame, normalGop) {
  const script = `// Auto-generated by fg · ffgac pict_type_script
// Frame 0 = real I, then periodic I every NORMAL_GOP frames up to MOSH_START,
// then P forever (no automatic keyframes after the melt begins).
let frame_num = 0;
const MOSH_START = ${moshStartFrame};
const NORMAL_GOP = ${normalGop};

export function setup() {
  frame_num = 0;
}

export function pict_type_func() {
  const f = frame_num++;
  if (f === 0) return "I";
  if (f < MOSH_START) return (f % NORMAL_GOP === 0) ? "I" : "P";
  return "P";
}
`;
  fs.writeFileSync(filePath, script);
}

function writeFreezeMvScript(filePath, moshStartFrame) {
  const script = `// Auto-generated by fg · ffedit glitch_frame script
// Freezes motion vectors from MOSH_START onward, so every frame after it
// re-applies the same MV block against decaying residual data — the melt.
let frame_num = 0;
const MOSH_START = ${moshStartFrame};
let saved_mv = null;

export function setup(args) {
  args.features = [ "mv" ];
  frame_num = 0;
  saved_mv = null;
}

export function glitch_frame(frame) {
  const f = frame_num++;
  const fwd = frame.mv && frame.mv.forward;
  if (!fwd) return;
  if (f < MOSH_START) return;

  if (f === MOSH_START) {
    saved_mv = JSON.parse(JSON.stringify(fwd));
  }

  for (let i = 0; i < fwd.length; i++) {
    const row = fwd[i];
    const savedRow = saved_mv[i];
    if (!savedRow) continue;
    for (let j = 0; j < row.length; j++) {
      const sv = savedRow[j];
      if (sv) {
        row[j][0] = sv[0];
        row[j][1] = sv[1];
      }
    }
  }
}
`;
  fs.writeFileSync(filePath, script);
}

/**
 * Run the full datamosh pipeline.
 *
 * @param {object} opts
 * @param {string} opts.inputPath         — source video
 * @param {string} opts.outputPath        — destination .avi path
 * @param {number} opts.moshStartSeconds  — seconds into the video the melt begins
 * @param {string} [opts.ffgacBin]        — override ffgac binary path
 * @param {string} [opts.ffeditBin]       — override ffedit binary path
 * @param {string} [opts.ffprobeBin]      — override ffprobe binary path
 * @param {number} [opts.normalGop=30]    — keyframe interval before the mosh point
 * @param {number} [opts.quality=3]       — ffgac -q:v (2=best, 31=worst)
 * @param {boolean} [opts.keepIntermediate=false]
 * @param {string} [opts.workDir]         — override temp dir (else a fresh mkdtemp)
 *
 * @returns {Promise<{outputPath:string, fps:number, totalFrames:?number, moshStartFrame:number}>}
 */
async function datamosh(opts) {
  const {
    inputPath, outputPath, moshStartSeconds,
    ffgacBin, ffeditBin, ffprobeBin,
    normalGop = 30, quality = 3,
    keepIntermediate = false, workDir,
  } = opts;

  const ffgac   = resolveBin('FFGAC_BIN',   ffgacBin,   'ffgac');
  const ffedit  = resolveBin('FFEDIT_BIN',  ffeditBin,  'ffedit');
  const ffprobe = resolveBin('FFPROBE_BIN', ffprobeBin, 'ffprobe');

  if (!await fileExists(inputPath)) {
    throw new DatamoshError(`Input file not found: ${inputPath}`);
  }
  if (!(moshStartSeconds >= 0)) {
    throw new DatamoshError('moshStartSeconds must be >= 0');
  }
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });

  const fps  = await probeFps(ffprobe, inputPath);
  const totalFrames = await probeFrameCount(ffprobe, inputPath);
  const moshStartFrame = Math.max(1, Math.round(moshStartSeconds * fps));

  if (totalFrames != null && moshStartFrame >= totalFrames) {
    throw new DatamoshError(
      `moshStartSeconds (${moshStartSeconds}s → frame ${moshStartFrame}) ` +
      `is at or past the end of the video (${totalFrames} frames total).`
    );
  }

  const usingExternalWorkDir = !!workDir;
  const tmpDir = workDir
    ? path.resolve(workDir)
    : await fsp.mkdtemp(path.join(os.tmpdir(), 'fg-datamosh-'));
  fs.mkdirSync(tmpDir, { recursive: true });

  try {
    const pictTypeScript = path.join(tmpDir, 'pict_type.js');
    const freezeMvScript = path.join(tmpDir, 'freeze_mv.js');
    const intermediate   = path.join(tmpDir, '_intermediate.avi');

    writePictTypeScript(pictTypeScript, moshStartFrame, normalGop);
    writeFreezeMvScript(freezeMvScript, moshStartFrame);

    // Stage 1: ffgac — dumb-encode with forced motion vectors, no I-macroblock
    // refresh in P frames, and no automatic keyframes after frame 0.
    await run([
      ffgac,
      '-y',
      '-i', inputPath,
      '-c:v', 'mpeg4',
      '-mpv_flags', '+forcemv+nopimb',
      '-g', '999999',
      '-sc_threshold', '1000000000',
      '-pict_type_script', pictTypeScript,
      '-q:v', String(quality),
      intermediate,
    ], 'ffgac encode');

    // Stage 2: ffedit — freeze motion vectors from the mosh point on.
    await run([
      ffedit,
      '-y',
      '-i', intermediate,
      '-f', 'mv',
      '-s', freezeMvScript,
      '-o', outputPath,
    ], 'ffedit motion-vector freeze');

    let intermediateKept = '';
    if (keepIntermediate) {
      const kept = outputPath.replace(/(\.[^.]+)?$/, '_intermediate$1') || (outputPath + '_intermediate.avi');
      fs.copyFileSync(intermediate, kept);
      intermediateKept = kept;
    }

    return {
      outputPath,
      fps,
      totalFrames,
      moshStartFrame,
      intermediatePath: intermediateKept,
    };
  } finally {
    if (!usingExternalWorkDir) {
      try { await fsp.rm(tmpDir, { recursive: true, force: true }); } catch {}
    }
  }
}

module.exports = { datamosh, datamoshStream, DatamoshError, run, resolveBin, fileExists, probeFps, probeFrameCount };

/**
 * Streaming variant of `datamosh` for privacy-first pipelines.
 *
 * Writes the upload to a private temp file, runs the pipeline into a second
 * private temp file, then streams the result via the given Response. Both
 * temp files are removed in `finally`, so the server never persists the
 * output (and never serves it via a URL after the response ends).
 *
 * @param {object} opts
 * @param {string}            opts.inputPath       — already-on-disk input file
 * @param {import('http').ServerResponse} opts.res — Express/Node response to stream to
 * @param {string}            [opts.filename]      — value for Content-Disposition
 * @param {object}            [...rest]            — passed through to `datamosh()`
 */
async function datamoshStream(opts) {
  const { inputPath, res, filename = 'output.avi', ...rest } = opts;

  const tmpOut = path.join(os.tmpdir(), `fg-mosh-out-${process.pid}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}.avi`);
  const tmpDir = await fsp.mkdtemp(path.join(os.tmpdir(), 'fg-datamosh-'));

  try {
    const result = await datamosh({
      ...rest,
      inputPath,
      outputPath: tmpOut,
      workDir:    tmpDir,
    });

    const stat = await fsp.stat(tmpOut);
    res.setHeader('Content-Type',        'video/x-msvideo');
    res.setHeader('Content-Length',      String(stat.size));
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.setHeader('Cache-Control',       'no-store');
    res.setHeader('X-Fg-Fps',            String(result.fps));
    res.setHeader('X-Fg-Mosh-Frame',     String(result.moshStartFrame));
    if (result.totalFrames != null) {
      res.setHeader('X-Fg-Total-Frames', String(result.totalFrames));
    }

    await pipeline(
      fs.createReadStream(tmpOut),
      res,
      { end: true }
    );

    return result;
  } finally {
    try { await fsp.rm(tmpOut, { force: true }); } catch {}
    try { await fsp.rm(tmpDir, { recursive: true, force: true }); } catch {}
  }
}