export function buildDatamoshScript(media, params = {}) {
  const {
    interpolate   = false,
    scaleFactor   = 1,
    targetFps     = 60,
    keepAudio     = true,
    outputWidth   = 1280,
  } = params;

  const input = media?.name || 'input.mp4';
  const L = [];
  const $ = s => L.push(s);

  $('#!/usr/bin/env bash');
  $('# ════════════════════════════════════════════════════');
  $('# Datamosh script — generated by fg · FFmpeg GUI');
  $('# Linux / macOS. Run from the folder containing your video.');
  $('# Requires: ffmpeg, ffprobe  with libxvid support');
  $('# ════════════════════════════════════════════════════');
  $('');
  $(`INPUT="${input}"`);
  $('');

  $('# ── Step 1: Encode as libxvid (generates clean I-frames) ──');
  if (interpolate && scaleFactor > 1) {
    $('ffmpeg -i "$INPUT" \\');
    $(`  -vf "minterpolate=fps=${targetFps}:mi_mode=mci,scale=${scaleFactor}*iw:${scaleFactor}*ih" \\`);
    $('  -vcodec libxvid -q:v 1 -g 1000 -qmin 1 -qmax 1 -flags qpel+mv4 -an -y xvid_video.avi');
  } else if (interpolate) {
    $('ffmpeg -i "$INPUT" \\');
    $(`  -vf "minterpolate=fps=${targetFps}:mi_mode=mci" \\`);
    $('  -vcodec libxvid -q:v 1 -g 1000 -qmin 1 -qmax 1 -flags qpel+mv4 -an -y xvid_video.avi');
  } else if (scaleFactor > 1) {
    $('ffmpeg -i "$INPUT" \\');
    $(`  -vf "scale=${scaleFactor}*iw:${scaleFactor}*ih" \\`);
    $('  -vcodec libxvid -q:v 1 -g 1000 -qmin 1 -qmax 1 -flags qpel+mv4 -an -y xvid_video.avi');
  } else {
    $('ffmpeg -i "$INPUT" \\');
    $('  -vcodec libxvid -q:v 1 -g 1000 -qmin 1 -qmax 1 -flags qpel+mv4 -an -y xvid_video.avi');
  }
  $('');

  $('# ── Step 2: Extract raw frames ──');
  $('mkdir -p frames/save');
  $('ffmpeg -i xvid_video.avi -vcodec copy -start_number 0 frames/f_%04d.raw');
  $('');

  $('# ── Step 3: Find I-frame (keyframe) positions ──');
  $('echo ""');
  $('echo "I-frames are at these positions (skip frame 0000 — keep it):"');
  $('ffprobe -loglevel error -select_streams v:0 \\');
  $('  -show_entries packet=flags -of flat=h=0 \\');
  $('  xvid_video.avi | grep "K_" | grep -oP \'(?<=\\.)\\d+\'');
  $('echo ""');
  $('');

  $('# ── Step 4: Remove I-frames to create datamosh effect ──');
  $('# Replace NNNN with each I-frame number you want to glitch.');
  $('# DO NOT remove frame 0000 (the first frame).');
  $('# Duplicate the NEXT frame to keep total frame count (keeps audio sync).');
  $('#');
  $('# cd frames');
  $('# mv f_NNNN.raw save/');
  $('# cp f_NNNN_NEXT.raw f_NNNN.raw   # e.g. cp f_0154.raw f_0153.raw');
  $('# cd ..');
  $('# (repeat for every I-frame you want to mosh)');
  $('');

  $('# ── Step 5: Reassemble raw frames into AVI ──');
  $('# Frames must be in sorted order — ls | sort handles this for zero-padded names.');
  $('cd frames && ls f_*.raw | sort | xargs cat > ../edited_video.avi && cd ..');
  $('');

  $('# ── Step 6: Final encode ──');
  if (keepAudio) {
    $('ffmpeg -i edited_video.avi -i "$INPUT" \\');
    $(`  -vf scale=${outputWidth}:-2 \\`);
    $('  -map 0:v:0 -map 1:a:0 \\');
    $('  -vcodec libx264 -crf 18 -pix_fmt yuv420p \\');
    $('  final_datamosh.mp4');
  } else {
    $('ffmpeg -i edited_video.avi \\');
    $(`  -vf scale=${outputWidth}:-2 \\`);
    $('  -vcodec libx264 -crf 18 -pix_fmt yuv420p -an \\');
    $('  final_datamosh.mp4');
  }
  $('');
  $('echo "Done! Output: final_datamosh.mp4"');
  $('echo "You can delete xvid_video.avi and edited_video.avi when satisfied."');

  return L.join('\n');
}